### PR TITLE
fix for flatbuffers v2

### PR DESCRIPTION
**Pull request by japm48**
There was a rename on a field.
Hopefully, this is all it takes for it to work...

### CODE REVIEW

**Comment by japm48** [comment]
Not yet... Please do not merge.

**Comment by japm48** [comment]
Ok, the problem seems to be that even if the `.fbs` files get compiled, the provided `_generated.h` is installed by default instead of the newly built ones. Only the new ones are compatible with the new version, so projects that import this (like inspectrum) fail to compile immediately (at `#include`).
So, an incompatible version is installed.
Any suggestions on how to convince CMake to install the correct one?

**Comment by jacobagilbert** [comment]
We have an internal fix for this that installs the prebuilt headers, then the built headers (if they exist). i'll get that pushed shortly.

**Comment by jacobagilbert** [comment]
@japm48 this is a good fix and I'm happy to merge, but can you please remove the added `default:` case? Its not relevant to this particular issue.

**Comment by jacobagilbert** [comment]
I cherry picked the relevant commit onto master so I am closing this. The build warning (and this commit) will be addressed in v1.0.

Thanks @japm48

**Comment by jacobagilbert** [comment]
Oh, one more thing @japm48, the issue with generated headers not being installed was also applied to this branch in 94445d48ab2827776ed51249e44db376bed82394

**Pull request closed without merging**
